import type { Metadata } from "next";
import "../styles/globals.css";
import React from "react";
import Providers from "@/utils/provider";

export const metadata: Metadata = {
  title: "Ask AI",
  description: "Generated by SSL.ir",
  icons: {
    icon: "/assets/images/site-logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
